server:
  port: 8080

spring:
  ai:
    deepseek:
      api-key: sk-d3206036c41c4031af6ec76588613e50
      base-url: https://api.deepseek.com
      chat:
        options:
#          v3模型
          model: deepseek-chat #使用哪个模型
          temperature: 0.8 #温度值：值越高（如 0.8 或更高）， 增加随机性，生成内容更多样化、富有创造性；
#          deepseek-R1 模型
#          model: deepseek-reasoner
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: qwen3:4b
          temperature: 0.7
    zhipuai:
      base-url: https://open.bigmodel.cn/api/paas # 智谱 AI 的请求 URL, 可不填，默认值为 open.bigmodel.cn/api/paas
      api-key: 44d2341d17f942699130aa4f209711a2.FDNwPc96t9xhaIgV # 填写智谱 AI 的 API Key, 该成你自己的
      chat:
        options: # 模型参数
          model: glm-4-air # 模型名称，使用智谱 AI 哪个模型
          temperature: 0.7 # 温度值
    openai:
      base-url: https://api.zhizengzeng.com/v1 # OpenAI 服务的访问地址，这里使用的第三方代理商：智增增
      api-key: sk-zk28b15112c26b4b51ed6f08f71e3fe2b806844ef2955a4f  # 填写智增增的 API Key, 该成你自己的
      chat:
        options:
          model: gpt-4o # 模型名称
          temperature: 0.7 # 温度值
logging:
  level:
    org.springframework.ai.chat.client.advisor: debug
